### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by stoklasa** [sunnankar/bm#106]
Hello, it would be lovely to contribute and translate your page to Czech. I have c1 level English, so I think I can help.

**Comment by sunnankar** [comment]
@stoklasa That would be great! These two pages would be a good place to start:

https://github.com/sunnankar/bm/tree/gh-pages/translations
https://www.bitcoinmining.com/best-bitcoin-cloud-mining-contract-reviews/
https://www.bitcoinmining.com/getting-started/

Submitting via pull request would be the easiest to administer.

**Comment by sumitsarode** [comment]
Hi
I can do the above translations in marathi.. how can I go ahead to contribute
