### ISSUE TITLE
PT-BR. How to translate

### ISSUE THREAD

**Issue by programonauta** [sunnankar/bm#35]
Hi,
I'm interesting in translate to Brazilian Portuguese.

How to proceed? Could you give the instructions?

**Comment by sunnankar** [comment]
@programonauta You could start with the index page here: https://github.com/sunnankar/bm/blob/gh-pages/pt/index.md

You could translate it and then submit the pull request.

If you want to do the subtitles then you could add it to this folder:

https://github.com/sunnankar/bm/tree/gh-pages/materials/wibm_video/v1

We could really use the help. Thanks!

**Comment by Fedya-Mercuriev** [comment]
Hi, interested in translating to Russian. Got translator education and expirience. Could provide me with instructions If a vacancy is still available?

**Comment by sunnankar** [comment]
@Fedya-Mercuriev You could start with the index page here: https://github.com/sunnankar/bm/blob/gh-pages/ru/index.md

You could translate it and then submit the pull request.

If you want to do the subtitles then you could add it to this folder:

https://github.com/sunnankar/bm/tree/gh-pages/materials/wibm_video/v1

We could really use the help. Thanks!

**Comment by kweros** [comment]
I did pull requests for portuguese translation in January. Until today, I've got response.
Can you help me?
