### ISSUE TITLE
I would love to help translating the page into Spanish

### ISSUE THREAD

**Issue by delphikybean** [sunnankar/bm#44]
I you still need help there.
I also will need a little tutorial on how to work, I see the pull request section but I dont know how to use them.

**Comment by sunnankar** [comment]
@delphikybean I think these articles might be helpful:

https://help.github.com/articles/creating-a-pull-request/
https://help.github.com/articles/using-pull-requests/
https://www.youtube.com/watch?v=YTbRzhQju4c
