### ISSUE TITLE
Wanna be added as collaborator

### ISSUE THREAD

**Issue by santy2001** [sunnankar/bm#53]
Hi, i just wanna be added as collaborator of the bitcoin.org , to participate actively and could merge pull request to the site , and also give us a hand in the process of makin easiest the bitcoin ,

my user is santy2001 , please add me as collaborator in the settings of the bitcoinmining.com, at the right of Graphs page.

I really appreciated.

**Comment by Pafc07** [comment]
Hi, I want to be added as a collaborator of the bitcoin.org, to participate actively.

My user is Pafc07, how can I be added?

Thank you

**Comment by sunnankar** [comment]
@santy2001 @Pafc07 You can submit pull requests to the project which can be merged by the maintainer. For security purposes, we are currently not expanding the people with merge access.
